"""Play cat-reaction voice clips in response to tracking Events.

Maps an `Event` to a "situation" key, picks a random voice variant clip for that
situation (`<situation>__<voice>.wav`, generated by tools/gen_cat_audio.py), and
plays it via `afplay`. Per-situation cooldown avoids spamming. The player is a
plain `BehaviorBus` subscriber; playback is injectable for tests.

Situation map:
  cat appears, far/small  -> cat_appear_far     ("Come here, meow meow!")
  cat appears, near/big   -> cat_appear_near     ("Easy there, meow meow, I'm not your food.")
  cat disappears          -> cat_leave           ("Aww, bye bye, meow meow.")
  person & cat intersect  -> intersect_look | intersect_benice  (random)
"""
from __future__ import annotations

import logging
import random
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_AUDIO_DIR = Path("~/.projectart/audio/cat").expanduser()


def afplay(path: Path) -> None:
    """Non-blocking playback via the macOS `afplay` CLI."""
    subprocess.Popen(["afplay", str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


@dataclass(slots=True)
class CatAudioConfig:
    audio_dir: Path = DEFAULT_AUDIO_DIR
    cooldown_s: float = 1.5
    enabled: bool = True
    cat_class: str = "cat"
    person_class: str = "person"


class CatAudioPlayer:
    def __init__(self, config: CatAudioConfig | None = None,
                 play: Callable[[Path], None] | None = None,
                 rng: random.Random | None = None):
        self.cfg = config or CatAudioConfig()
        self._play = play or afplay
        self._rng = rng or random.Random()
        self._last: dict[str, float] = {}  # situation -> ts last played

    def situation_for(self, ev) -> str | None:
        cat, person = self.cfg.cat_class, self.cfg.person_class
        if ev.kind == "appear" and ev.class_name == cat:
            return "cat_appear_near" if ev.size == "near" else "cat_appear_far"
        if ev.kind == "disappear" and ev.class_name == cat:
            return "cat_leave"
        if ev.kind == "intersect" and {ev.class_name, ev.other_class} == {cat, person}:
            return self._rng.choice(["intersect_look", "intersect_benice"])
        return None

    def clip_for(self, situation: str) -> Path | None:
        clips = sorted(self.cfg.audio_dir.glob(f"{situation}__*.wav"))
        return self._rng.choice(clips) if clips else None

    def on_event(self, ev) -> Path | None:
        """Decide + play a clip for an Event. Returns the clip played, or None."""
        if not self.cfg.enabled:
            return None
        situation = self.situation_for(ev)
        if situation is None:
            return None
        last = self._last.get(situation)
        if last is not None and (ev.ts - last) < self.cfg.cooldown_s:
            return None
        clip = self.clip_for(situation)
        if clip is None:
            log.debug("no clip for situation %r in %s", situation, self.cfg.audio_dir)
            return None
        self._last[situation] = ev.ts
        try:
            self._play(clip)
        except Exception:
            log.exception("failed to play %s", clip)
        return clip

    def subscribe(self, bus) -> None:
        """Attach to a BehaviorBus so every Event flows through `on_event`."""
        bus.on("event", lambda *, event: self.on_event(event))
