"""Play cat-reaction voice clips in response to tracking Events.

Maps an `Event` to a "situation" key, picks a random voice variant clip for that
situation (`<situation>__<voice>.wav`, generated by tools/gen_cat_audio.py), and
plays it via `afplay`. Per-situation cooldown avoids spamming. The player is a
plain `BehaviorBus` subscriber; playback is injectable for tests.

Situation map:
  cat appears, far/small  -> cat_appear_far     ("Come here, meow meow!")
  cat appears, near/big   -> cat_appear_near     ("Easy there, meow meow, I'm not your food.")
  cat disappears          -> cat_leave           ("Aww, bye bye, meow meow.")
  person & cat intersect  -> intersect_look | intersect_benice  (random)
"""
from __future__ import annotations

import logging
import random
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_AUDIO_DIR = Path("~/.projectart/audio").expanduser()  # searched recursively (cat/, people/)


def _slug(name: str) -> str:
    return name.lower().replace(" ", "_")


def afplay(path: Path) -> None:
    """Non-blocking playback to the system DEFAULT output via the macOS `afplay` CLI."""
    subprocess.Popen(["afplay", str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def play_on_device(path: Path, device_index: int) -> None:
    """Non-blocking playback to a SPECIFIC output device via sounddevice/soundfile
    (leaves the system default output untouched)."""
    import sounddevice as sd
    import soundfile as sf

    data, samplerate = sf.read(str(path), dtype="float32")
    sd.play(data, samplerate, device=device_index)  # returns immediately


@dataclass(slots=True)
class CatAudioConfig:
    audio_dir: Path = DEFAULT_AUDIO_DIR
    cooldown_s: float = 1.5
    enabled: bool = True
    cat_class: str = "cat"
    person_class: str = "person"
    device: str | None = None  # output device name (substring); None = default output


class CatAudioPlayer:
    def __init__(self, config: CatAudioConfig | None = None,
                 play: Callable[[Path], None] | None = None,
                 rng: random.Random | None = None):
        self.cfg = config or CatAudioConfig()
        self._rng = rng or random.Random()
        self._last: dict[str, float] = {}  # situation -> ts last played
        self._play = play or self._resolve_play()

    def _resolve_play(self) -> Callable[[Path], None]:
        """Route to a named device via sounddevice if `cfg.device` is set and found,
        else fall back to `afplay` (system default output)."""
        if not self.cfg.device:
            return afplay
        from .devices import find_device

        idx = find_device(self.cfg.device)
        if idx is None:
            log.warning("audio device %r not found; using default output", self.cfg.device)
            return afplay
        log.info("cat audio routed to device [%d] %r", idx, self.cfg.device)
        return lambda path: play_on_device(path, idx)

    def situations_for(self, ev) -> list[str]:
        """Ordered candidate situation keys for an Event (most specific first).
        Name-aware keys (greet_<name>, intersect_*_<name>) fall back to generic."""
        cat, person = self.cfg.cat_class, self.cfg.person_class
        slug = _slug(ev.name) if getattr(ev, "name", None) else None
        if ev.kind == "recognize" and slug:
            return [f"greet_{slug}"]
        if ev.kind == "appear" and ev.class_name == cat:
            return ["cat_appear_near" if ev.size == "near" else "cat_appear_far"]
        if ev.kind == "disappear" and ev.class_name == cat:
            return ["cat_leave"]
        if ev.kind == "intersect" and {ev.class_name, ev.other_class} == {cat, person}:
            base = self._rng.choice(["intersect_look", "intersect_benice"])
            return [f"{base}_{slug}", base] if slug else [base]
        return []

    def clip_for(self, situation: str) -> Path | None:
        clips = sorted(self.cfg.audio_dir.rglob(f"{situation}__*.wav"))
        return self._rng.choice(clips) if clips else None

    def on_event(self, ev) -> Path | None:
        """Decide + play a clip for an Event. Returns the clip played, or None."""
        if not self.cfg.enabled:
            return None
        candidates = self.situations_for(ev)
        if not candidates:
            return None
        key = candidates[0]  # cooldown keyed on the most-specific situation
        last = self._last.get(key)
        if last is not None and (ev.ts - last) < self.cfg.cooldown_s:
            return None
        clip = None
        for situation in candidates:
            clip = self.clip_for(situation)
            if clip is not None:
                break
        if clip is None:
            log.info("no audio clip for %r in %s (did you run the gen_*_audio.py tools?)",
                     candidates, self.cfg.audio_dir)
            return None
        self._last[key] = ev.ts
        try:
            self._play(clip)
        except Exception:
            log.exception("failed to play %s", clip)
        return clip

    def subscribe(self, bus) -> None:
        """Attach to a BehaviorBus so every Event flows through `on_event`."""
        bus.on("event", lambda *, event: self.on_event(event))
